name: Build, Package, and Release Electron App

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write
  deployments: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch: [arm64, x64]
        platform: [windows, linux, macos]

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置最新的 Node.js 版本
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: 安装依赖
        run: npm install

      - name: 打包应用
        run: npm run make

      - name: 发布至 GitHub Releases
        uses: softprops/action-gh-release@v2.0.9
        with:
          tag_name: latest
          name: ${{github.ref_name}}
          files: ${{ github.workspace }}/out/make/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
